# site settings
title: Quien te financia
email: info@ciudadanointeligente.org
description: Hasta que no sepamos quién los financia nos gobierna un poder invisible.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://quientefinancia.cl" # the base hostname & protocol for your site
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
analytics: 'UA-41822715-1'
basedomain: quientefinancia.cl

# build settings
markdown: kramdown
