# site settings
title: No más cohecho
email: info@ciudadanointeligente.org
description: La corrupción se detiene con cambios profundos
baseurl: "https://nomascohecho.cl" # "http://quientefinancia.cl" ## the subpath of your site, e.g. /blog/
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
analytics: 'UA-41822715-11'
basedomain: nomascohecho.cl #quientefinancia.cl

# build settings
markdown: kramdown

collections:
  congressmen:
    output: true
  lawyers:
    output: true
