# site settings
title: No más cohecho
email: info@ciudadanointeligente.org
description: La corrupción se detiene con cambios profundos
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nomascohecho.cl"
twitter_username: ciudadania_i
github_username:  ciudadanointeligente
analytics: 'G-31T3XTW1TL'
basedomain: nomascohecho.cl #quientefinancia.cl

# build settings
markdown: kramdown

collections:
  congressmen:
    output: true
  lawyers:
    output: true
